@startuml
'https://plantuml.com/class-diagram

interface Factory {
  +Product factoryMethod1()
  +Product factoryMethod2()
}
interface Product {
  +void method()
}
class ConcreteFactory

Factory <|-- ConcreteFactory
Product <|-- Product1
Product <|-- Product2

Factory -left--> Product

@enduml