spring:
  datasource:
    url: jdbc:mysql://10.0.0.3:3306/xxzj?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mybatis/*.xml