spring:
  cloud:
    zookeeper:
      connect-string: localhost:2181,localhost:2182,localhost:2183
      discovery:
        enabled: true
        prefer-ip-address: true
  application:
    name: zookeeper-server
  profiles:
    active: s1