spring:
  application:
    name: feign-client
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
# feign client config not work in ribbon loadbalancer, use ribbon config
# feign client config worked in spring-cloud-loadbalancer
feign:
  client:
    config:
      waitServiceApi:
        connectTimeout: 60000
        readTimeout: 120000
        loggerLevel: FULL
      echoServiceApi:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: FULL
      queryServiceApi:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: FULL
  httpclient:
    enabled: true
feign-server:
  ribbon:
    ConnectTimeout: 60000
    ReadTimeout: 150000